version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000-8015:8000"  # Multiple ports for scaling
    environment:
      DEBUG: ${DEBUG}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_HOST: ${BOT_HOST}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BACKEND_ORIGIN: ${BACKEND_ORIGIN}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
    depends_on:
      - db
      - redis
    command:
      - sh
      - -lc
      - >
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        
        exec gunicorn core.asgi:application
        -k uvicorn.workers.UvicornWorker
        --bind 0.0.0.0:8000
        --timeout 60
        --workers ${GUNICORN_WORKERS:-8}
        --worker-connections ${WORKER_CONNECTIONS:-1000}
        --max-requests ${MAX_REQUESTS:-1000}
        --max-requests-jitter ${MAX_REQUESTS_JITTER:-100}
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./logs:/app/log
      - .:/app

  db:
    image: pgvector/pgvector:pg17
    container_name: ewa_db_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_MAX_CONNECTIONS: 500
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ewa_redis
    command: >
      redis-server
      --maxmemory 2gb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    volumes:
      - redis_data:/data
      
  # Fast worker - handles all your RAG tasks
  worker-fast:
    build: .
    command: >
      celery -A core worker
      --loglevel=INFO
      --queues=fast,default
      --concurrency=${WORKER_FAST_CONCURRENCY:-8}
      --prefetch-multiplier=1
      --max-tasks-per-child=1000
      --autoscale=32,8
    environment:
      DEBUG: ${DEBUG}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_HOST: ${BOT_HOST}
    depends_on: 
      - redis
      - db
    volumes:
      - .:/app

  # Scheduler (only one)
  beat:
    build: .
    command: celery -A core beat --loglevel=INFO
    environment:
      DEBUG: ${DEBUG}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on: 
      - redis
      - db
    volumes:
      - .:/app

  flower:
    build: .
    command: celery -A core flower --loglevel=INFO --port=5555
    environment:
      DEBUG: ${DEBUG}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on: 
      - redis
      - db
    volumes:
      - .:/app
    ports:
      - "5555:5555"

volumes:
  db_data:
  redis_data: