# Generated by Django 5.2.5 on 2025-09-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rag_system', '0004_embedding_embeddingdata_delete_data'),
        ('telegram_client', '0004_alter_botclient_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatsession', to='telegram_client.botclient')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('owner', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('embedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rag_system.embedding')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='miniapp.chatsession')),
            ],
        ),
    ]
