# Generated by Django 5.2.5 on 2025-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.CharField(choices=[('user', 'user'), ('system', 'system')], max_length=6),
        ),
    ]
