# Generated by Django 5.2.5 on 2025-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0002_alter_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('chat', 'chat'), ('skynet', 'skynet')], default='chat', max_length=6),
        ),
    ]
