# Generated by Django 5.2.5 on 2025-09-22 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_chatsession_mode'),
        ('rag_system', '0007_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rag_system.roles'),
        ),
        migrations.AddField(
            model_name='message',
            name='summarize_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='summarize_start',
            field=models.BooleanField(default=False),
        ),
    ]
