# Generated by Django 5.2.5 on 2025-10-01 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0004_chatsession_current_role_message_summarize_end_and_more'),
        ('rag_system', '0008_roles_summarize_behaviour'),
        ('telegram_client', '0004_alter_botclient_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'verbose_name': 'Сессия чата', 'verbose_name_plural': 'Сессии чатов'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='bot_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatsession', to='telegram_client.botclient', verbose_name='Бот-клиент'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='current_role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='rag_system.roles', verbose_name='Текущая роль'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('chat', 'chat'), ('skynet', 'skynet')], default='chat', max_length=6, verbose_name='Режим работы'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='embedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rag_system.embedding', verbose_name='Эмбеддинг'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.CharField(choices=[('user', 'user'), ('system', 'system')], max_length=6, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='miniapp.chatsession', verbose_name='Сессия чата'),
        ),
        migrations.AlterField(
            model_name='message',
            name='summarize_end',
            field=models.BooleanField(default=False, verbose_name='Конец суммаризации'),
        ),
        migrations.AlterField(
            model_name='message',
            name='summarize_start',
            field=models.BooleanField(default=False, verbose_name='Начало суммаризации'),
        ),
    ]
