# Generated by Django 5.2.5 on 2025-08-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0004_alter_attachmenttobutton_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='✅ Проверен')),
                ('chat_id', models.BigIntegerField(db_index=True, verbose_name='💬 ID чата')),
                ('first_name', models.CharField(max_length=100, verbose_name='🧑 Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='👨\u200d👩\u200d👦 Фамилия')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='📱 Имя пользователя Telegram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='🕰 Время регистрации')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='⏳ Последняя активность')),
            ],
            options={
                'verbose_name': '🤖 Клиент бота',
                'verbose_name_plural': '🤖 Клиенты бота',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='BotClientSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='⏳ Обновлено')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='telegram_client.botclient', verbose_name='👤 Клиент')),
                ('current_button', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='telegram.buttontree', verbose_name='🔘 Текущая кнопка')),
            ],
            options={
                'verbose_name': '📌 Сессия клиента',
                'verbose_name_plural': '📌 Сессии клиентов',
            },
        ),
    ]
