# Generated by Django 5.2.5 on 2025-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botclient',
            name='phone_number',
            field=models.CharField(default=5555555555555555555555, max_length=30),
            preserve_default=False,
        ),
    ]
