# Generated by Django 5.2.5 on 2025-09-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_client', '0002_botclient_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='botclient',
            name='is_logined',
            field=models.BooleanField(default=False, verbose_name='✅ логин'),
        ),
    ]
