# Generated by Django 5.2.5 on 2025-09-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_client', '0003_botclient_is_logined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botclient',
            name='chat_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='💬 ID чата'),
        ),
    ]
