# Generated by Django 5.2.5 on 2025-10-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_client', '0004_alter_botclient_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botclient',
            name='client_id',
            field=models.CharField(default='3055', max_length=100),
        ),
    ]
