# Generated by Django 5.2.5 on 2025-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_client', '0005_botclient_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botclient',
            name='client_id',
            field=models.CharField(default='not set', max_length=100),
        ),
    ]
