# Generated by Django 5.2.5 on 2025-10-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_client', '0006_alter_botclient_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='🧑 Имя'),
        ),
        migrations.AlterField(
            model_name='botclient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
