# Generated by Django 5.2.5 on 2025-10-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_client', '0007_alter_botclient_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botclient',
            name='ai_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='botclient',
            name='grade',
            field=models.CharField(default='GradePassivePartner', max_length=220),
        ),
    ]
