# Generated by Django 5.2.5 on 2025-08-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentToButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source_type', models.CharField(choices=[('text', 'text'), ('file', 'file'), ('video', 'video'), ('image', 'image')], default='text', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='AtachmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.FileField(upload_to='tree-buttons/leaf-data')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='telegram.attachmenttobutton')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='telegram.buttontree')),
            ],
        ),
        migrations.AddField(
            model_name='attachmenttobutton',
            name='button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.buttontree'),
        ),
    ]
