# Generated by Django 5.2.5 on 2025-08-25 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atachmentdata',
            name='attachment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='telegram.attachmenttobutton'),
        ),
    ]
