# Generated by Django 5.2.5 on 2025-08-25 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_atachmentdata_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atachmentdata',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='telegram.attachmenttobutton'),
        ),
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='button',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telegram.buttontree'),
        ),
    ]
