# Generated by Django 5.2.5 on 2025-08-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_atachmentdata_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='source_type',
            field=models.CharField(choices=[('text', 'text'), ('file', 'file'), ('video', 'video'), ('image', 'image'), ('video_image', 'video_image')], default='text', max_length=15),
        ),
    ]
