# Generated by Django 5.2.5 on 2025-08-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_attachmenttobutton_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='button',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='telegram.buttontree'),
        ),
    ]
