# Generated by Django 5.2.5 on 2025-09-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_alter_attachmenttobutton_button'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtachmentData',
            new_name='AttachmentData',
        ),
    ]
