# Generated by Django 5.2.5 on 2025-09-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_rename_atachmentdata_attachmentdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentdata',
            options={'verbose_name': '📂 Данные вложения', 'verbose_name_plural': '📂 Файлы вложений'},
        ),
        migrations.AlterModelOptions(
            name='attachmenttobutton',
            options={'verbose_name': '📎 Вложение к кнопке', 'verbose_name_plural': '📎 Вложения к кнопкам'},
        ),
        migrations.AlterModelOptions(
            name='buttontree',
            options={'verbose_name': '🔘 Кнопка', 'verbose_name_plural': '🔘 Дерево кнопок'},
        ),
        migrations.AlterField(
            model_name='attachmentdata',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='telegram.attachmenttobutton', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='attachmentdata',
            name='source',
            field=models.FileField(upload_to='tree-buttons/leaf-data', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='button',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='telegram.buttontree', verbose_name='Кнопка'),
        ),
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='source_type',
            field=models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('video', 'Видео'), ('image', 'Изображение'), ('video_image', 'Видео или изображение')], default='text', max_length=15, verbose_name='Тип источника'),
        ),
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='text',
            field=models.TextField(verbose_name='Текст вложения'),
        ),
        migrations.AlterField(
            model_name='buttontree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='telegram.buttontree', verbose_name='Родительская кнопка'),
        ),
        migrations.AlterField(
            model_name='buttontree',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст кнопки'),
        ),
    ]
