# Generated by Django 5.2.5 on 2025-09-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_alter_attachmentdata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachmentdata',
            options={'verbose_name': '📂 Данные вложения', 'verbose_name_plural': '📂 Файлы вложений'},
        ),
        migrations.AlterModelOptions(
            name='attachmenttobutton',
            options={'verbose_name': '📎 Вложение к кнопке', 'verbose_name_plural': '📎 Вложения к кнопкам'},
        ),
        migrations.AlterField(
            model_name='attachmentdata',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='telegram.attachmenttobutton', verbose_name='Вложение'),
        ),
        migrations.AlterField(
            model_name='attachmentdata',
            name='source',
            field=models.FileField(upload_to='tree-buttons/leaf-data', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='source_type',
            field=models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('video', 'Видео'), ('image', 'Изображение'), ('video_image', 'Видео или изображение')], default='text', max_length=15, verbose_name='Тип источника'),
        ),
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='text',
            field=models.TextField(verbose_name='Текст вложения'),
        ),
    ]
