# Generated by Django 5.2.5 on 2025-09-29 13:07

import telegram.models.buttonTree
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_alter_attachmentdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentdata',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Формат: JPEG, макс. размер: 200 kB, макс. размеры: 320x320px', null=True, upload_to='thumbnails/', validators=[telegram.models.buttonTree.validate_thumbnail], verbose_name='изображение видеофайла'),
        ),
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='source_type',
            field=models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('video', 'Видео'), ('image', 'Изображение'), ('video_image', 'Видео или изображение'), ('video_image_file', 'Видео, изображение, файл ')], default='text', max_length=16, verbose_name='Тип источника'),
        ),
    ]
