# Generated by Django 5.2.5 on 2025-10-01 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_attachmentdata_thumbnail_and_more'),
        ('telegram_client', '0004_alter_botclient_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadTestProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('beauty', 'Красота'), ('weight_loss', 'Похудение'), ('energy', 'Энергия'), ('brain', 'Мозг'), ('edema', 'Отеки'), ('stress', 'Стресс'), ('joints', 'Суставы')], max_length=20)),
                ('priority', models.CharField(choices=[('primary', 'Основной'), ('secondary', 'Вторичный')], default='primary', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('dosage', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BadTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='attachmenttobutton',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вложения'),
        ),
        migrations.CreateModel(
            name='BadTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('points_beauty', models.IntegerField(default=0)),
                ('points_weight_loss', models.IntegerField(default=0)),
                ('points_energy', models.IntegerField(default=0)),
                ('points_brain', models.IntegerField(default=0)),
                ('points_edema', models.IntegerField(default=0)),
                ('points_stress', models.IntegerField(default=0)),
                ('points_joints', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='telegram.badtestquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BadTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_data', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_client.botclient')),
                ('current_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.badtestquestion')),
            ],
            options={
                'unique_together': {('client', 'is_completed')},
            },
        ),
    ]
