# Generated by Django 5.2.5 on 2025-10-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_badtestproduct_badtestquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badtestanswer',
            options={'ordering': ['question__order', 'order'], 'verbose_name': 'Ответ BAD теста', 'verbose_name_plural': 'Ответы BAD теста'},
        ),
        migrations.AlterModelOptions(
            name='badtestproduct',
            options={'verbose_name': 'Продукт БАД', 'verbose_name_plural': 'Продукты БАД'},
        ),
        migrations.AlterModelOptions(
            name='badtestquestion',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос BAD теста', 'verbose_name_plural': 'Вопросы BAD теста'},
        ),
        migrations.AlterModelOptions(
            name='badtestsession',
            options={'verbose_name': 'Сессия BAD теста', 'verbose_name_plural': 'Сессии BAD теста'},
        ),
    ]
