# Generated by Django 5.2.5 on 2025-10-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0012_alter_badtestanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buttontree',
            unique_together={('parent', 'text')},
        ),
    ]
