# Generated by Django 5.2.5 on 2025-10-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0013_alter_buttontree_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buttontree',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='buttontree',
            constraint=models.UniqueConstraint(fields=('parent', 'text'), name='unique_button_when_parent_exists'),
        ),
        migrations.AddConstraint(
            model_name='buttontree',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('text',), name='unique_root_button_text'),
        ),
    ]
