# Generated by Django 5.2.5 on 2025-10-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0014_alter_buttontree_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttontree',
            options={'ordering': ['text'], 'verbose_name': '🔘 Кнопка', 'verbose_name_plural': '🔘 Дерево кнопок'},
        ),
    ]
