# Generated by Django 5.2.5 on 2025-10-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0015_alter_buttontree_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttontree',
            options={'ordering': ['-weight', 'text'], 'verbose_name': '🔘 Кнопка', 'verbose_name_plural': '🔘 Дерево кнопок'},
        ),
        migrations.AddField(
            model_name='buttontree',
            name='weight',
            field=models.IntegerField(default=0, help_text='Чем выше число, тем выше приоритет в списке. При одинаковом весе сортируется по тексту.', verbose_name='Вес'),
        ),
    ]
