# Generated by Django 5.2.5 on 2025-08-20 12:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='embedded_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
