# Generated by Django 5.2.5 on 2025-08-20 13:40

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0002_alter_data_embedded_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='embedded_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
