# Generated by Django 5.2.5 on 2025-09-04 07:05

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0003_alter_data_embedded_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='Исходный текст')),
                ('embedded_vector', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Векторное представление')),
            ],
            options={
                'verbose_name': 'Встраивание',
                'verbose_name_plural': 'Встраивания',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='data/', verbose_name='Файл')),
                ('embedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='rag_system.embedding', verbose_name='Встраивание')),
            ],
            options={
                'verbose_name': 'Данные встраивания',
                'verbose_name_plural': 'Данные встраиваний',
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
