# Generated by Django 5.2.5 on 2025-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0004_embedding_embeddingdata_delete_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rules', models.TextField(verbose_name='Основные правила')),
                ('base_information', models.TextField(verbose_name='Базовая информация')),
                ('gpt_model', models.CharField(max_length=50, verbose_name='GPT-модель')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('last_message_count', models.PositiveIntegerField(default=10, verbose_name='Количество последних сообщений')),
            ],
            options={
                'verbose_name': 'Утилита',
                'verbose_name_plural': 'Утилиты',
            },
        ),
    ]
