# Generated by Django 5.2.5 on 2025-09-20 17:53

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0005_utils'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedding',
            options={'verbose_name': 'Эмбеддинг', 'verbose_name_plural': 'Эмбеддинг'},
        ),
        migrations.AddField(
            model_name='utils',
            name='choose_embedding_rule',
            field=models.TextField(default='add embedding id if you include answer from this embedding if the answer doesnt required info below return -1', verbose_name='Правило выбора эмбеддинга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='embedding',
            name='embedded_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True, verbose_name='Векторный эмбеддинг'),
        ),
    ]
