# Generated by Django 5.2.5 on 2025-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0006_alter_embedding_options_utils_choose_embedding_rule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour', models.TextField(verbose_name='Поведение')),
                ('name', models.CharField(unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
    ]
