# Generated by Django 5.2.5 on 2025-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0007_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='summarize_behaviour',
            field=models.TextField(default='Here you should summarize based on the history and your behaviour', verbose_name='Поведение итоги'),
        ),
    ]
