# Generated by Django 5.2.5 on 2025-10-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_system', '0008_roles_summarize_behaviour'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='portret',
            field=models.TextField(default='Think yourself as person', verbose_name='портрет'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='summarize_behaviour',
            field=models.TextField(default='Here you should shortly summarize user behaviour on the given history and put score from 10.', verbose_name='Поведение итоги'),
        ),
    ]
